// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: SentReaction.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from SentReaction.proto</summary>
public static partial class SentReactionReflection {

  #region Descriptor
  /// <summary>File descriptor for SentReaction.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static SentReactionReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "ChJTZW50UmVhY3Rpb24ucHJvdG8iSgoMU2VudFJlYWN0aW9uEhQKDGNvbnRl",
          "bnRfdHlwZRgBIAIoDRISCgpjb250ZW50X2lkGAIgAigEEhAKCGF3YXJkX2lk",
          "GAMgAigN"));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { },
        new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::SentReaction), global::SentReaction.Parser, new[]{ "ContentType", "ContentId", "AwardId" }, null, null, null, null)
        }));
  }
  #endregion

}
#region Messages
public sealed partial class SentReaction : pb::IMessage<SentReaction>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<SentReaction> _parser = new pb::MessageParser<SentReaction>(() => new SentReaction());
  private pb::UnknownFieldSet _unknownFields;
  private int _hasBits0;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<SentReaction> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::SentReactionReflection.Descriptor.MessageTypes[0]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public SentReaction() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public SentReaction(SentReaction other) : this() {
    _hasBits0 = other._hasBits0;
    contentType_ = other.contentType_;
    contentId_ = other.contentId_;
    awardId_ = other.awardId_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public SentReaction Clone() {
    return new SentReaction(this);
  }

  /// <summary>Field number for the "content_type" field.</summary>
  public const int ContentTypeFieldNumber = 1;
  private readonly static uint ContentTypeDefaultValue = 0;

  private uint contentType_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public uint ContentType {
    get { if ((_hasBits0 & 1) != 0) { return contentType_; } else { return ContentTypeDefaultValue; } }
    set {
      _hasBits0 |= 1;
      contentType_ = value;
    }
  }
  /// <summary>Gets whether the "content_type" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool HasContentType {
    get { return (_hasBits0 & 1) != 0; }
  }
  /// <summary>Clears the value of the "content_type" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void ClearContentType() {
    _hasBits0 &= ~1;
  }

  /// <summary>Field number for the "content_id" field.</summary>
  public const int ContentIdFieldNumber = 2;
  private readonly static ulong ContentIdDefaultValue = 0UL;

  private ulong contentId_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public ulong ContentId {
    get { if ((_hasBits0 & 2) != 0) { return contentId_; } else { return ContentIdDefaultValue; } }
    set {
      _hasBits0 |= 2;
      contentId_ = value;
    }
  }
  /// <summary>Gets whether the "content_id" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool HasContentId {
    get { return (_hasBits0 & 2) != 0; }
  }
  /// <summary>Clears the value of the "content_id" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void ClearContentId() {
    _hasBits0 &= ~2;
  }

  /// <summary>Field number for the "award_id" field.</summary>
  public const int AwardIdFieldNumber = 3;
  private readonly static uint AwardIdDefaultValue = 0;

  private uint awardId_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public uint AwardId {
    get { if ((_hasBits0 & 4) != 0) { return awardId_; } else { return AwardIdDefaultValue; } }
    set {
      _hasBits0 |= 4;
      awardId_ = value;
    }
  }
  /// <summary>Gets whether the "award_id" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool HasAwardId {
    get { return (_hasBits0 & 4) != 0; }
  }
  /// <summary>Clears the value of the "award_id" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void ClearAwardId() {
    _hasBits0 &= ~4;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as SentReaction);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(SentReaction other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (ContentType != other.ContentType) return false;
    if (ContentId != other.ContentId) return false;
    if (AwardId != other.AwardId) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (HasContentType) hash ^= ContentType.GetHashCode();
    if (HasContentId) hash ^= ContentId.GetHashCode();
    if (HasAwardId) hash ^= AwardId.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (HasContentType) {
      output.WriteRawTag(8);
      output.WriteUInt32(ContentType);
    }
    if (HasContentId) {
      output.WriteRawTag(16);
      output.WriteUInt64(ContentId);
    }
    if (HasAwardId) {
      output.WriteRawTag(24);
      output.WriteUInt32(AwardId);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (HasContentType) {
      output.WriteRawTag(8);
      output.WriteUInt32(ContentType);
    }
    if (HasContentId) {
      output.WriteRawTag(16);
      output.WriteUInt64(ContentId);
    }
    if (HasAwardId) {
      output.WriteRawTag(24);
      output.WriteUInt32(AwardId);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (HasContentType) {
      size += 1 + pb::CodedOutputStream.ComputeUInt32Size(ContentType);
    }
    if (HasContentId) {
      size += 1 + pb::CodedOutputStream.ComputeUInt64Size(ContentId);
    }
    if (HasAwardId) {
      size += 1 + pb::CodedOutputStream.ComputeUInt32Size(AwardId);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(SentReaction other) {
    if (other == null) {
      return;
    }
    if (other.HasContentType) {
      ContentType = other.ContentType;
    }
    if (other.HasContentId) {
      ContentId = other.ContentId;
    }
    if (other.HasAwardId) {
      AwardId = other.AwardId;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          ContentType = input.ReadUInt32();
          break;
        }
        case 16: {
          ContentId = input.ReadUInt64();
          break;
        }
        case 24: {
          AwardId = input.ReadUInt32();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 8: {
          ContentType = input.ReadUInt32();
          break;
        }
        case 16: {
          ContentId = input.ReadUInt64();
          break;
        }
        case 24: {
          AwardId = input.ReadUInt32();
          break;
        }
      }
    }
  }
  #endif

}

#endregion


#endregion Designer generated code
